name: Build

on: [pull_request, push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependency
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
