name: DEPLOY PRODUCTION

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Get commit message
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log --format=%s -n 1)
          echo "commitmsg=${COMMIT_MESSAGE}" >> $GITHUB_ENV
      - name: Show commit message
        run : echo "$commitmsg"

      - name: Deploy to dokku
        id: deploy
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          dokku-host: ${{ secrets.DOKKU_HOST_PROD }}
          app-name: 'wallet'
          remote-branch: 'master'
